global:
  scrape_interval:     15s
scrape_configs:

  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['monitoring.homelab.local:9091']

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['monitoring.homelab.local:9100','services.homelab.local:9100','nextcloud-serv.homelab.local:9100','jellyfin-serv.homelab.local:9100','guacamole-serv.homelab.local:9100','vault-serv.homelab.local:9100','proxy.homelab.local:9100','nfs.homelab.local:9100','pihole-serv.homelab.local:9100']

  #- job_name: 'pihole'
  #  static_configs:
  #   - targets: ['192.168.1.9:9617']