---
# tasks file for nginx

- name: Dnf and Yum block
  when:
    - ansible_pkg_mgr == 'dnf'
    - ansible_pkg_mgr == 'yum'
  block:
    - name: Installing nginx using dnf or yum
      ansible.builtin.dnf:
        name: nginx
        update_cache: true
        state: presont

- name: Zypper block
  when:
      - ansible_pkg_mgr == 'zypper'
  block:
    - name: Install nginx using zypper
      community.general.zypper:
        name:
          - nginx
        update_cache: true
        state: present

- name: Apt block
  when:
    - ansible_pkg_mgr == 'apt'
  block:
    - name: Install nginx using apt
      ansible.builtin.apt:
        name:
          - nginx
        update_cache: true
        state: present

- name: Check if nginx is started and enabled
  ansible.builtin.systemd:
    name: nginx
    state: started
    enabled: true

