---

- name: Dnf and Yum block
  when:
    - ansible_pkg_mgr == 'dnf'
    - ansible_pkg_mgr == 'yum'
  block:
    - name: Installing using dnf or yum
      ansible.builtin.dnf:
        name: "{{ pkg_name }}"
        update_cache: true
        state: "{{ pkg_state }}"

- name: Zypper block
  when:
    - ansible_pkg_mgr == 'zypper'
  block:
    - name: Installing using zypper
      community.general.zypper:
        name:
          - "{{ pkg_name }}"
        update_cache: true
        state: "{{ pkg_state }}"

- name: Install firewald on apt
  when:
    - ansible_pkg_mgr == 'apt'
  block:
    - name: Installing using apt
      ansible.builtin.apt:
        name:
          - "{{ pkg_name }}"
        update_cache: true
        state: "{{ pkg_state }}"

- name: Check if firewalld is started
  ansible.builtin.systemd:
    name: "{{ pkg_name }}"
    state: started
    enabled: true
